# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authserver.proto

require 'google/protobuf'


descriptor_data = "\n\x10\x61uthserver.proto\x12\nauthserver\"9\n\x11\x41uthServerRequest\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"K\n\x12\x41uthServerResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x32\x63\n\x11\x41uthServerService\x12N\n\rHandleRequest\x12\x1d.authserver.AuthServerRequest\x1a\x1e.authserver.AuthServerResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Authserver
  AuthServerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authserver.AuthServerRequest").msgclass
  AuthServerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("authserver.AuthServerResponse").msgclass
end
